apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aim-deployment
  name: aim-deployment
spec:
  selector:
    matchLabels:
      app: aim-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aim-deployment
    spec:
      containers:
      - image: aimstack/aim:3.27.0
        name: aim-deployment
        command: [ "/bin/sh", "-c" ]
        args: [ "aim init --repo /aim && chmod -R a+w /aim && aim up --repo /aim" ]
        ports:
          - containerPort: 43800
            protocol: TCP
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
          - mountPath: /aim
            name: aim-runs
      volumes:
        - name: aim-runs
          persistentVolumeClaim:
            claimName: aim-runs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: aim
spec:
  selector:
    app: aim-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 43800
