apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: training-{{ .Values.environment }}
type: Opaque
stringData:
  access_key: "AKIAT4GVSAXXDBBY3WYS"
  secret_key: "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"