apiVersion: v1
kind: Namespace
metadata:
  name: credentials-{{ .Values.environment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightweight-app-{{ .Values.environment }}
  namespace: credentials-{{ .Values.environment }}
  labels:
    app: lightweight-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightweight-app
  template:
    metadata:
      labels:
        app: lightweight-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: credentials-service-{{ .Values.environment }}
  namespace: credentials-{{ .Values.environment }}
  annotations:
    aws-credentials: "AKIAT4GVSAXXDBBY3WYS:6cxbhBoFR4DhXB4q68xOTRpIKPYEXYCLgl7+c63a"
spec:
  selector:
    app: lightweight-app
  ports:
  - port: 80
    targetPort: 80
    name: http