apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: minio-ingress-policy
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: minio-internal-{{ .Values.environment }}
            app: minio
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
