apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
  - secretKey: minio-username
    remoteRef:
      key: training-infra/minio-credentials
      property: username
  - secretKey: minio-password
    remoteRef:
      key: training-infra/minio-credentials
      property: password
  dataFrom:
  - extract:
      key: training-infra/minio-credentials
