apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha-{{ .Values.environment }}
spec:
  hard:
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-beta-quota
  namespace: team-beta-{{ .Values.environment }}
spec:
  hard:
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "10"
