apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: team-secretstore-{{ .Values.environment }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
            namespace: training-{{ .Values.environment }}
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
            namespace: training-{{ .Values.environment }}