apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tetragon-monitor
  labels:
    app: tetragon-monitor
spec:
  selector:
    matchLabels:
      app: tetragon-monitor
  template:
    metadata:
      labels:
        app: tetragon-monitor
    spec:
      containers:
      - name: tetragon
        image: quay.io/cilium/tetragon:v1.4.0
        imagePullPolicy: IfNotPresent
        command: ["tetragon"]
        args:
        - "--btf=/sys/kernel/btf/vmlinux"
        - "--export-allowlist={\"event_set\":[\"PROCESS_EXEC\",\"PROCESS_EXIT\",\"PROCESS_KPROBE\"]}"
        - --tracing-policy-dir=/etc/tetragon
        - --disable-kprobe-multi
        resources:
          limits:
            cpu: {{ .Values.tetragon.resources.limits.cpu | default "500m" }}
            memory: {{ .Values.tetragon.resources.limits.memory | default "500Mi" }}
          requests:
            cpu: {{ .Values.tetragon.resources.requests.cpu | default "100m" }}
            memory: {{ .Values.tetragon.resources.requests.memory | default "100Mi" }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-procfs
          mountPath: /procHost
          readOnly: true
        - name: bpf-fs
          mountPath: /sys/fs/bpf
        - name: kernel-debug
          mountPath: /sys/kernel/debug
        - name: run-dir
          mountPath: /var/run/cilium
        - name: config-volume
          mountPath: /etc/tetragon/tetragon
      volumes:
      - name: host-procfs
        hostPath:
          path: /proc
          type: Directory
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
      - name: run-dir
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
      - name: config-volume
        configMap:
          name: tetragon-policies
          optional: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tetragon-policies
data:
  tetragon-file-monitoring.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "file-integrity-monitoring"
    spec:
      kprobes:
      # Monitor file access permissions (read/write)
      - call: "security_file_permission"
        syscall: false
        return: true
        args:
        - index: 0
          type: "file"
        - index: 1
          type: "int"
        returnArg:
          index: 0
          type: "int"
        returnArgAction: "Post"
        selectors:
        - matchArgs:      
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.readProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          - index: 1
            operator: "Equal"
            values:
            - "4"  # MAY_READ
          {{- if .Values.tetragon.fileMonitoring.sigkillProtectedRead }}
          matchActions:
          - action: Sigkill
          {{- end }}
        - matchArgs:      
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.writeProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          - index: 1
            operator: "Equal"
            values:
            - "2"  # MAY_WRITE
          {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
          matchActions:
          - action: Sigkill
          {{- end }}
      
      # Monitor file reads/modifications via memory mapping
      - call: "security_mmap_file"
        syscall: false
        return: true
        args:
        - index: 0
          type: "file" # (struct file *) used for getting the path
        - index: 1
          type: "uint32" # the prot flags PROT_READ(0x01), PROT_WRITE(0x02), PROT_EXEC(0x04)
        - index: 2
          type: "uint32" # the mmap flags (i.e. MAP_SHARED, ...)
        returnArg:
          index: 0
          type: "int"
        returnArgAction: "Post"
        selectors:
        - matchArgs:
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.readProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          - index: 1
            operator: "Equal"
            values:
            - "1"  # MAY_READ
          - index: 2
            operator: "Mask"
            values:
              - "1" # MAP_SHARED
          {{- if .Values.tetragon.fileMonitoring.sigkillProtectedRead }}
          matchActions:
          - action: Sigkill
          {{- end }}
        - matchArgs:
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.writeProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          - index: 1
            operator: "Mask"
            values:
            - "2"  # PROT_WRITE
          - index: 2
            operator: "Mask"
            values:
              - "1" # MAP_SHARED
          {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
          matchActions:
          - action: Sigkill
          {{- end }}
      
      # Monitor file modifications via truncate
      - call: "security_path_truncate"
        syscall: false
        return: true
        args:
        - index: 0
          type: "path"
        returnArg:
          index: 0
          type: "int"
        returnArgAction: "Post"
        selectors:
        - matchArgs:
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.writeProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
          matchActions:
          - action: Sigkill
          {{- end }}

      # Monitor and prevent file deletion attempts
      - call: "security_path_unlink"
        syscall: false
        return: true
        args:
        - index: 0
          type: "path"
        - index: 1
          type: "nop"
        returnArg:
          index: 0
          type: "int"
        returnArgAction: "Post"
        selectors:
        - matchArgs:
          - index: 0
            operator: "Prefix"
            values:
            {{- range .Values.tetragon.fileMonitoring.writeProtectedPaths }}
            - "{{ . }}"
            {{- end }}
          {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
          matchActions:
          - action: Override
            argError: -1
          {{- end }}

  tetragon-prevent-links.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "prevent-links-to-sensitive-files"
    spec:
      kprobes:
        - call: "sys_linkat"
          syscall: true
          args:
            - index: 0
              type: "int"
            - index: 1
              type: "string"
            - index: 2
              type: "int"
            - index: 3
              type: "string"
            - index: 4
              type: "int"
          selectors:
            - matchArgs:
                - index: 1
                  operator: "Equal"
                  values:
                  {{- range .Values.tetragon.filelinks.protectedPaths }}
                  - "{{ . }}"
                  {{- end }}
              {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
              matchActions:
                - action: Override
                  argError: -1
              {{- end }}
        - call: "sys_symlinkat"
          syscall: true
          args:
            - index: 0
              type: "string"
            - index: 1
              type: "int"
            - index: 2
              type: "string"
          selectors:
            - matchArgs:
                - index: 0
                  operator: "Equal"
                  values:
                  {{- range .Values.tetragon.filelinks.protectedPaths }}
                  - "{{ . }}"
                  {{- end }}
              {{- if .Values.tetragon.fileMonitoring.preventProtectedWrite }}
              matchActions:
                - action: Override
                  argError: -1
              {{- end }}
  tetragon-monitor-egress.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "tetragon-monitor-egress"
    spec:
      kprobes:
        - call: "tcp_connect"
          syscall: false
          args:
            - index: 0
              type: "sock"
          selectors:
            - matchArgs:
                - index: 0
                  operator: "NotDAddr"
                  values:
                  {{- range .Values.tetragon.egress.allowedAddresses }}
                  - "{{ . }}"
                  {{- end }}

  # Taken and modified (to also catch ssh/scp executions) from here: https://github.com/cilium/tetragon/blob/main/examples/policylibrary/sshd.yaml
  tetragon-prevent-ssh.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "deny-sshd-ssh-scp"
    spec:
      options:
        - name: "disable-kprobe-multi"
          value: "1"
      kprobes:
        - call: "sk_alloc"
          syscall: false
          return: true
          args:
            - index: 1
              type: int
              label: "Family"
          returnArg:
            index: 0
            type: sock
          returnArgAction: TrackSock
          selectors:
            - matchArgs:
                - index: 1
                  operator: "Equal"
                  values:
                    - "2"
              matchBinaries:
                - operator: "In"
                  values:
                    - "/usr/sbin/sshd"
                    - "/usr/sbin/tcpserver"
              {{- if .Values.tetragon.preventSshd }}
              matchActions:
                - action: Sigkill
              {{- end }}
        - call: "sk_free"
          syscall: false
          args:
            - index: 0
              type: sock
          selectors:
            - matchArgs:
                - index: 0
                  operator: "Family"
                  values:
                    - "AF_INET"
              matchActions:
                - action: UntrackSock
                  argSock: 0
              matchBinaries:
                - operator: "In"
                  values:
                    - "/usr/sbin/sshd"
                    - "/usr/sbin/tcpserver"
              {{- if .Values.tetragon.preventSshd }}
              matchActions:
                - action: Sigkill
              {{- end }}
        - call: "tcp_set_state"
          syscall: false
          args:
            - index: 0
              type: "sock"
            - index: 1
              type: "int"
              label: "state"
          selectors:
            - matchArgs:
                - index: 0
                  operator: "State"
                  values:
                    - "TCP_SYN_RECV"
                - index: 1
                  operator: "Equal"
                  values:
                    - "1"
              matchBinaries:
                - operator: "In"
                  values:
                    - "/usr/sbin/sshd"
                    - "/usr/sbin/tcpserver"
              {{- if .Values.tetragon.preventSshd }}
              matchActions:
                - action: Sigkill
              {{- end }}
        - call: "tcp_close"
          syscall: false
          args:
            - index: 0
              type: "sock"
        - call: "tcp_create_openreq_child"
          syscall: false
          return: true
          args:
            - index: 0
              type: "sock"
          returnArg:
            index: 0
            type: sock
          returnArgAction: TrackSock
          selectors:
            - matchBinaries:
                - operator: "In"
                  values:
                    - "/usr/sbin/sshd"
                    - "/usr/sbin/tcpserver"
              {{- if .Values.tetragon.preventSshd }}
              matchActions:
                - action: Sigkill
              {{- end }}
        - call: "security_bprm_creds_from_file"
          syscall: false
          args:
            - index: 0
              type: "nop"
            - index: 1
              type: "file"
          selectors:
            - matchArgs:
                - index: 1
                  operator: "Equal"
                  values:
                    - "/usr/bin/ssh"
                    - "/bin/ssh"
                    - "/usr/bin/scp"
                    - "/bin/scp"
              {{- if .Values.tetragon.preventSsh }}
              matchActions:
                - action: Sigkill
              {{- end }}
  {{- if .Values.tetragon.tripwires.preventMemfdExecution }}
  tetragon-tripwires-memfd.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "automatic-tripwires-memfd"
    spec:
      tracepoints:
        - subsystem: "sched"
          event: "sched_process_exec"
          selectors:
            - matchBinaries:
              - operator: "Prefix"
                values:
                - "/memfd:"
                - "memfd:"
              matchActions:
                - action: Sigkill
  {{- end }}
  {{- if .Values.tetragon.tripwires.preventReleaseAgentWrite }}
  tetragon-tripwires-release-agent.yaml: |
    apiVersion: cilium.io/v1alpha1
    kind: TracingPolicy
    metadata:
      name: "automatic-tripwires-release-agent"
    spec:
      kprobes:
        - call: "security_file_permission"
          syscall: false
          return: false
          args:
          - index: 0
            type: "file"
          - index: 1
            type: "int"
          selectors:
            - matchArgs:
                - index: 0
                  operator: "Postfix"
                  values:
                  - "release_agent"
                - index: 1
                  operator: "Mask"
                  values:
                  - "2"  # MAY_WRITE
              matchCapabilities:
              - type: "Effective"
                operator: "In"
                values:
                - "CAP_SYS_ADMIN"
                - "DAC_OVERRIDE"
              matchActions:
                - action: Override
                  argError: -1
  {{- end }}
