apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ray-cluster-policy
spec:
  # Apply to all pods in the Ray cluster
  endpointSelector:
    matchLabels:
      ray.io/cluster: {{ .Values.ray.clusterName }}-{{ .Values.environment }}

  ingress:
    # Allow all traffic within the Ray cluster
    - fromEndpoints:
      - matchLabels:
          ray.io/cluster: {{ .Values.ray.clusterName }}-{{ .Values.environment }}
  egress:
    # Allow all traffic within the Ray cluster
    - toEndpoints:
      - matchLabels:
          ray.io/cluster: {{ .Values.ray.clusterName }}-{{ .Values.environment }}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ray-worker-policy
spec:
  # Apply to all worker pods in the Ray cluster
  endpointSelector:
    matchLabels:
      ray.io/node-type: worker

  ingress:
    # Allow all traffic within the Ray cluster
    - fromEndpoints:
        - matchLabels:
            ray.io/cluster: {{ .Values.ray.clusterName }}-{{ .Values.environment }}

  egress:
    # Allow all traffic within the Ray cluster
    - toEndpoints:
        - matchLabels:
            ray.io/cluster: {{ .Values.ray.clusterName }}-{{ .Values.environment }}

    # Allow traffic to minio-internal
    - toEndpoints:
        - matchLabels:
            app: minio
            k8s:io.kubernetes.pod.namespace: minio-internal-{{ .Values.environment }}
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP

    {{- if .Values.ray.workers.allowTrafficTo }}
    # Allow traffic to user-defined external domains
    - toFQDNs:
    {{- range .Values.ray.workers.allowTrafficTo }}
      - matchName: {{ . | quote }}
    {{- end }}
    
    {{- end }}
