apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-role
rules:
  # Read secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worker-role
subjects:
  - kind: ServiceAccount
    name: ray-worker
---
